- name: Set up editorconfig
  copy:
    src: .editorconfig
    dest: ~/.editorconfig
    force: yes

- name: Install vscode
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install vscode CLI
  lineinfile:
    line: export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
    path: ~/.zshrc
    create: yes

- name: Install vscode extensions
  command: code --install-extension {{ item }}
  loop:
    - coenraads.bracket-pair-colorizer
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - mohsen1.prettify-json
    - mrmlnc.vscode-duplicate

# TODO(jbotros): Set more preferences (e.g., newline on save)
