- name: Install common packages
  homebrew:
    name:
      - curl
      - git
      - shellcheck
      - wget
    state: present

# TODO(jbotros): Figure out how to allow in accessibility list
- name: Install clipboard manager
  homebrew_cask:
    name: flycut
    state: present

- name: Install window manager
  homebrew_cask:
    name: rectangle
    state: present

- name: Install app store CLI
  homebrew:
    name: mas
    state: present

- name: Install notes app
  # Bear: https://apps.apple.com/us/app/bear/id1091189122?mt=12
  command: mas install 1091189122
